global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'rpi-monitor'

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.1.150:9100','192.168.1.151:9100','192.168.1.152:9100']

  - job_name: 'arm_exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.1.150:9243', 192.168.1.151:9243, 192.168.1.152:9243]

  - job_name: 'cadvisor'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.1.150:8098', 192.168.1.151:8098, 192.168.1.152:8098]
